zookeeper:
  build: ./zookeeper/framework
  restart: always
  ports:
    - "2181:2181"
  volumes:
    - ./backup/zookeeper:/tmp/zookeeper
kafka:
  build: ./kafka/framework
  restart: always
  ports:
    - "9092:9092"
  links:
    - zookeeper:zookeeper
nimbus:
  build: ./storm/framework/storm-nimbus
  restart: always
  ports:
    - "49772:3772"
    - "49773:3773"
    - "49627:6627"
    - "22"
  links:
    - zookeeper:zk
supervisor:
  build: ./storm/framework/storm-supervisor
  restart: always
  ports:
    - "8000"
    - "22"
  links:
    - nimbus:nimbus
    - zookeeper:zk
    - mongodb
stormui:
  build: ./storm/framework/storm-ui
  restart: always
  ports:
    - "22"
    - "8080:8080"
  links:
    - nimbus:nimbus
    - zookeeper:zk
