zookeeper:
  build: ./zookeeper/framework
  restart: always
  ports:
    - "2181:2181"
  # volumes:
  #   - ./backup/zookeeper:/tmp/zookeeper
kafka:
  build: ./kafka/framework
  restart: always
  ports:
    - "9092:9092"
  links:
    - zookeeper:zookeeper
nimbus:
  build: ./storm/framework/storm-nimbus
  restart: always
  ports:
    - "3772:3772"
    - "3773:3773"
    - "6627:6627"
  links:
    - zookeeper:zk
supervisor:
  build: ./storm/framework/storm-supervisor
  restart: always
  ports:
    - "8000"
  links:
    - nimbus:nimbus
    - zookeeper:zk
stormui:
  build: ./storm/framework/storm-ui
  restart: always
  ports:
    - "8080:8080"
  links:
    - nimbus:nimbus
    - zookeeper:zk
